config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get '/users/edit' => "users#edit", as: :create_profile
  # Defines the root path route ("/")
  root "posts#index", as: :dashboard

  resources :posts do 
    member do 
      patch 'like', to: 'likes#update'
    end
    resources :comments 
  end
  
  resources :comments do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create, :new, :update]

  #For reply form
  def new
    @comment = @commentable
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @post = @commentable
    if @comment.update(comment_params)
      redirect_to @post, notice: "Comment updated"
    else
      render :edit, notice: "Something went wrong, comment was not updated"
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @user = current_user.id
    # @comment = @post.comments.build(comment_params)
    @comment = @commentable.comments.build(comment_params)
    @comment.user_id = @user

    if @comment.save && @comment.commentable_type == 'Post' 
      @post = Post.find(params[:post_id])
      respond_to do |format|
        format.html {
          redirect_to dashboard_path, notice: 'Comment successfully created'
        }
        format.turbo_stream
      end
    elsif @comment.save && @comment.commentable_type == 'Comment'
      respond_to do |format|
        format.html {
          redirect_to dashboard_path, notice: 'Comment successfully created'
        }
        format.turbo_stream {
          render turbo_stream: turbo_stream.append("replies_for_comment_#{@comment.commentable_id}", 
                                                  partial: 'comments/reply',
                                                  locals: { comment: @comment } )
        }
      end
    else
      flash[:alert] = 'Comment can not be empty'
      #Redirect back to previous page where request originated or dashboard path if not available
      redirect_to request.referer || dashboard_path, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Comment successfully deleted' }
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove("comment_#{@comment.id}")
      }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :comment_id, :commentable_id)
  end

  def find_commentable
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:post_id]
      @commentable = Post.find_by_id(params[:post_id])
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def find_username(user_id)
    User.find(user_id).name
  end
  
  def post_for_this_comment(comment)
    Post.find(comment.commentable_id)
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <div class="card w-50 mx-auto border-dark border-1">
    <div class="card-body d-flex justify-content-between">
      <div>
        <div>
          <strong><%= find_username(comment.user_id) %></strong> commented: <%= comment.content %>
        </div>
        <%= turbo_frame_tag "replies_for_comment_#{comment.id}" do %>
          <% unless comment.comments.empty? %>
            <% comment.comments.take(slice ? 3 : comment.comments.size).each do |reply| %>
              <%= turbo_frame_tag "reply_#{reply.id}" do %>
                <div>
                  <%= render "comments/reply", comment: reply %>                 
                </div>
              <% end %>
            <% end %> 
          <% end %>
        <% end %>
        <div>
          <%= turbo_frame_tag "reply_for_comment_#{comment.id}" do %>
          <% end %>
        </div>
      </div>
      <%= render 'comments/comment_dropdown', comment: comment %>
    </div>
    <div class="mt-0 pt-0 d-flex gap-3 ml-3">
      <%= link_to 'Reply', new_comment_comment_path(comment.id),
                          data: {
                            turbo_frame: "reply_for_comment_#{comment.id}"
                          } %>
      <% if comment.comments.count > 3 && 
            (current_page?(dashboard_path) || 
            current_page?(:controller => 'users', :action => 'show'))%>
        <div>
          <%= link_to 'View more', post_path(comment.commentable),
                                  data: {
                                    turbo_frame: '_top'
                                  } %>
        </div>
      <% end %>
    </div>
  </div>
<% end %> 

app/views/comments/_comment_dropdown.html.erb
<div>
  <% if current_user.id == comment.user_id %>
    <div class="dropdown">
        <%= link_to "#",
                    class: "nav-link",
                    data: {
                      bs_toggle: "dropdown"
                    } do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="16" width="4" viewBox="0 0 128 512"><path d="M64 360a56 56 0 1 0 0 112 56 56 0 1 0 0-112zm0-160a56 56 0 1 0 0 112 56 56 0 1 0 0-112zM120 96A56 56 0 1 0 8 96a56 56 0 1 0 112 0z"/></svg>
        <% end %>
      <ul class="dropdown-menu">
        <%= button_to "Delete",
                    post_comment_path(comment.commentable_id, comment),
                    method: :delete,
                    class: 'dropdown-item btn btn-outline-danger btn-sm' %>
        <%= link_to "Edit", edit_post_comment_path(comment.commentable_id, comment),
                            class: 'dropdown-item btn btn-outline-secondary btn-sm',
                            data: {
                              turbo_frame: "comment_#{comment.id}"
                            } %>
      </ul>
    </div>
  <% end %>
</div>

app/views/comments/_comment_form.html.erb
<div class='text-center container'>
  <%= form_with model: [post,comment], 
                data: { 
                  controller: "reset-form",
                  action: 'turbo:submit-end->reset-form#reset' } do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='d-flex justify-content-center gap-2 mt-1'>
      <%= form.text_field :content, 
                          id: 'comment-form-size',
                          class: 'form-control',
                          placeholder: 'Write a comment...',
                          autofocus: true %>
      
      <%= form.submit class: "btn btn-primary" %>
    </div>
    
  <% end %>
</div>

app/views/comments/_reply.html.erb
<%= turbo_frame_tag "reply_for_#{comment.id}" do %>
  <div>
    <div>
      <strong><%= find_username(comment.user_id) %></strong> replied: <%= comment.content %>
    </div>
  </div>
<% end %>

app/views/comments/_reply_form.html.erb
<%= form_with model: [comment, Comment.new],
              data: { 
                controller: "reset-form",
                action: 'turbo:submit-end->reset-form#reset' } do |f| %>
  <%= f.text_field :content, placeholder: "Add a reply",
                            class: 'form-control' %>
  <%= f.submit "Reply", class: 'btn btn-primary btn-sm' %>
  <%= link_to "Cancel", post_path(comment.commentable),
                      class: 'btn btn-secondary btn-sm' %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments_for_#{@post.id}", @comment %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "comment_#{@comment.id}" do %> 
  <%= render partial: "comment_form", 
              locals: { 
                post: post_for_this_comment(@comment),
                comment: @comment
              } %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "reply_for_comment_#{@comment.id}" do %>
  <%= render 'reply_form', comment: @comment %>
<% end %>