config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get '/users/edit' => "users#edit", as: :create_profile
  # Defines the root path route ("/")
  root "posts#index", as: :dashboard

  resources :posts do 
    member do 
      patch 'like', to: 'likes#update'
    end
    resources :comments 
  end
  
  resources :comments do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Gravtastic
  gravtastic :secure => true,
              :size => 50,
              :default => "monsterid"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  validates :name, presence: true, length: { minimum: 2, maximum: 20}, on: :edit
  validates :email, presence: true, uniqueness: true

  has_many :posts
  has_many :comments
  #Active storage for avatar 
  has_one_attached :avatar
  
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
  has_many :followers, through: :passive_relationships

  after_create :send_welcome_email

  #follows a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    followings.include?(other_user)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
  end
  private 

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now!
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Github'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @pagy, @users = pagy(User.all)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path, notice: "Profile updated"
    else
      render :edit, notice: "Something went wrong, profile was not updated"
    end
  end

  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.all.ordered)
    @comment_slice = true
  end

  def following
    @user = User.find(params[:id])
    @pagy, @following = pagy(@user.followings.all)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers.all)
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_change_avatar_form.html.erb
<%= form_with model: user do |f| %>
  <%= f.label :avatar, "Profile" %>
  <%= f.file_field :avatar, class: 'form-control' %>
  <%= f.submit 'Submit', class: "btn btn-primary btn-sm" %>
<% end %>

app/views/users/_follow_button.html.erb
<div>
  <% if current_user != user && !current_user.following?(user) %>
    <%= render 'follow_form', relationship: current_user.active_relationships.build,
                              user: user %>
  <% elsif current_user.following?(user) %>
    <%= render 'unfollow_form', 
                relationship: current_user.active_relationships.find_by(followed_id: user.id) %>
  <% end %>
</div>

app/views/users/_follow_form.html.erb
<%= form_with model: relationship do |form| %>
  <%= form.hidden_field :followed_id, value: user.id  %>
  <%= form.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_list.html.erb
<div class="card w-50 container-xl mt-1">
  <div class="card-body d-grid">
    <div class="row">
      <div class="col">
        <%= render "profile_pic", user: user, size: [50,50] %>
        <%= link_to "#{user.name}", user_path(user), class: "text-nowrap" %>

        <div class="col">
          <%= user.followings.count %>
          <%= link_to "Following", following_user_path(user), class: "w-75 text-nowrap" %> 

          <%= user.followers.count %>
          <%= link_to "Followers", followers_user_path(user), class: "text-nowrap" %>
        </div>
      </div>
      
      <div class="col text-end mt-3">
        <%= render "follow_button", user: user %>
      </div>
    </div>
  </div>
</div>

app/views/users/_profile_form.html.erb
<div class='profile-form-container'>
  <%= form_with model: user do |form| %>

    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <%= form.label :name, "Username: " %>
    <%= form.text_field :name, placeholder:"Other users will see this name" %>
    <%= form.submit %>
  <% end %>
  
</div>

app/views/users/_profile_pic.html.erb
<% if user.avatar.attached? %>
  <%= image_tag user.avatar.variant(
    resize_and_pad: size
  ) %>
<% else %>
  <%= image_tag user.gravatar_url, 
                alt: "profile-picture" %> 
<% end %>

app/views/users/_unfollow_form.html.erb
<%= form_with model: relationship, method: :delete do |form| %>
  <%# <%= form.hidden_field :follower_id, value: user.id  %> 
  <%= form.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<%= link_to "Back", :back, class: 'fs-1 link-dark'%>
<div class="text-center">
  <h2>Edit profile</h2>
  <% if current_user.name.nil? %>
    Please create a username for other users to see
  <% end %>
  <%= render partial: 'profile_form', locals: { user: @user } %>
</div>

app/views/users/followers.html.erb
<%= link_to "Back", :back, class: 'fs-1 link-dark'%>
<div class="mt-3 mb-3 d-flex justify-content-center">
  <% if @user.followers.empty? %>
    <p class="fs-1">This user has no followers</p>
  <% else %>
    <%= render partial: 'follow_list', collection: @followers, as: :user %>
  <% end %>
</div>
<%= render partial: "shared/pagination", locals: { pagy: @pagy } %>

app/views/users/following.html.erb
<%= link_to "Back", :back, class: 'fs-1 link-dark'%>
<div class="mt-3 mb-3 container">
  <% if @user.followings.empty? %>
    <p class="fs-1">This user is not following anyone</p>
  <% else %>
    <%= render partial: 'follow_list', collection: @following, as: :user%>
  <% end %>
</div>
<%= render partial: "shared/pagination", locals: { pagy: @pagy } %>

app/views/users/index.html.erb
<div class='container'>
  <%= render partial: "follow_list", collection: @users, as: :user %>
  <%= render partial: "shared/pagination", locals: { pagy: @pagy } %>
</div>

app/views/users/new.html.erb
<h1>Welcome <%= current_user.email %></h1>
<h2>Please input your username (this is the name that other users will see)</h2>
<%= form_with model: @user do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Back", :back, class: 'fs-1 link-dark'%>
<div class="d-grid container-fluid">
  <div class="row">
    <div class="col-2">
      <%= render "profile_pic", user: @user, size: [50,50] %>
      <%= render "change_avatar_form", user: @user %>
      <h5 class="mt-0"><%= @user.name %></h5>
      <p><%= @user.email %></p>
      <div>
        <%= @user.followings.count %>
        <%= link_to "Following", following_user_path(@user), class: "link-dark" %> 
        
        <%= @user.followers.count %>
        <%= link_to "Followers", followers_user_path(@user), class: "link-dark" %>
      </div>
      <%= render 'follow_button', user: @user %>
    </div>
    <div class='col-10'>
      <h1 class='text-center'>All of <%= @user.name %>'s recent posts</h1>
      <% @posts.each do |post| %>
        <%= render post, path: post_path(post)  %>
        <%= turbo_frame_tag "comments_for_#{post.id}" do %>
          <% post.comments.each do |comment| %>
            <%= render comment, slice: @comment_slice %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: "shared/pagination", locals: { pagy: @pagy } %>