config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get '/users/edit' => "users#edit", as: :create_profile
  # Defines the root path route ("/")
  root "posts#index", as: :dashboard

  resources :posts do 
    member do 
      patch 'like', to: 'likes#update'
    end
    resources :comments 
  end
  
  resources :comments do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_display_post.html.erb
<div class="text-center container post-container">
  <%= post.user.name %> posted 
  <span class="post-title-container"><%= post.title %></span>
  <div class="post-body-container">
    <%= post.body %>
  </div>

  <% if current_user == post.user %>
    <%= form_with %>
  <% end %>
</div> 

app/views/shared/_navbar.html.erb
<nav id="stellar-nav" class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: 'navbar-brand' do %>
      <svg width="50px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>alpha-s</title><path d="M11,7A2,2 0 0,0 9,9V11A2,2 0 0,0 11,13H13V15H9V17H13A2,2 0 0,0 15,15V13A2,2 0 0,0 13,11H11V9H15V7H11Z" /></svg>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", dashboard_path, class: "nav-link active", "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Post", new_post_path, class:"nav-link", data: { turbo_frame: dom_id(Post.new) } %>
        </li> 
        <li class="nav-item">
          <%= link_to "Find Users", users_path, class:"nav-link" %>
        </li> 
      </ul>
      <form class="d-flex mx-lg-auto flex-grow-0" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav mx-auto">
        <%= render "users/profile_pic", user: current_user, size: [50,50] %>
        <li class="nav-item dropdown">
          <%= link_to "#{current_user.name}", "#",
                                            class: "nav-link dropdown-toggle",
                                            data: {
                                              bs_toggle: "dropdown"
                                            } %>
          <ul class="dropdown-menu">
            <%= link_to "Settings", edit_user_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%# <li><a class="dropdown-item" href="#">Display</a></li> %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item"%>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pagination.html.erb
<% if pagy && pagy.pages > 1 %>
  <div class="pagination mt-5 justify-content-center">
    <%== pagy_bootstrap_nav(pagy) %>
  </div>
<% end %>